[build]
  command = """
    rm -rf build-dir || true &&
    git clone --filter=blob:none https://github.com/ajay-kumar2109/Ghostchat build-dir &&
    cd build-dir &&
    pip install -r requirements.txt &&
    mkdir -p dist &&
    cp -r templates/* dist/ &&
    cp -r static dist/
  """
  publish = "build-dir/dist"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200