[build]
  command = """
    git clone --filter=blob:none https://github.com/ajay-kumar2109/Ghostchat build-dir && 
    cd build-dir && 
    pip install -r requirements.txt
  """
  publish = "build-dir/templates"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200